spring.config.import=optional:file:.env[.properties]

spring.application.name=ITAUtask

spring.data.mongodb.uri=${SPRING_DATA_MONGODB_URI}

logging.level.org.springframework.data.mongodb=DEBUG

# Intervalo em segundos utilizado para calcular as estatisticas
estatistica.intervalo-segundos=${ESTATISTICA_INTERVALO_SEGUNDOS}
server.port=${PORT}

management.endpoints.web.exposure.include=health,info,metrics
