spring.application.name=ITAUtask

# Intervalo em segundos utilizado para calcular as estatisticas
estatistica.intervalo-segundos=3600
server.port=${PORT:8080}

management.endpoints.web.exposure.include=health